import { PracticeTask } from '../types';

export const PRACTICE_TASKS: PracticeTask[] = [
  {
    id: 'pt-sql-1',
    skillId: 'sql',
    careerId: 'data-analyst',
    title: 'E-commerce Online Store Querying Practice',
    datasetName: 'GlobalTech Retail Store (50,000 Transactions)',
    datasetDescription: 'A relational schema containing `customers`, `orders`, `order_items`, and `products` tables spanning 24 months of sales.',
    tasks: [
      {
        id: 'st-1',
        description: 'Select all completed orders where order amount exceeds ₹1,000.',
        hint: 'Use SELECT ... FROM orders WHERE order_status = \'Completed\' AND order_amount > 1000;',
        solutionSnippet: `SELECT order_id, customer_id, order_date, order_amount
FROM orders
WHERE order_status = 'Completed' AND order_amount > 1000
ORDER BY order_amount DESC;`
      },
      {
        id: 'st-2',
        description: 'Calculate the total revenue generated by each product category.',
        hint: 'Join products with order_items, use SUM() and GROUP BY products.category.',
        solutionSnippet: `SELECT 
  p.category, 
  SUM(oi.quantity * oi.unit_price) AS category_revenue,
  COUNT(DISTINCT oi.order_id) AS order_count
FROM order_items oi
JOIN products p ON oi.product_id = p.id
GROUP BY p.category
ORDER BY category_revenue DESC;`
      },
      {
        id: 'st-3',
        description: 'Find the top 5 customers with the highest cumulative spend using a JOIN and GROUP BY.',
        hint: 'Join customers with orders, aggregate with SUM(order_amount), order by sum DESC, and LIMIT 5.',
        solutionSnippet: `SELECT 
  c.id, 
  c.full_name, 
  c.email,
  SUM(o.order_amount) AS total_spent
FROM customers c
JOIN orders o ON c.id = o.customer_id
WHERE o.order_status = 'Completed'
GROUP BY c.id, c.full_name, c.email
ORDER BY total_spent DESC
LIMIT 5;`
      },
      {
        id: 'st-4',
        description: 'Identify customers who registered in the database but have never made a purchase (LEFT JOIN where order is NULL).',
        hint: 'LEFT JOIN orders and check WHERE orders.id IS NULL.',
        solutionSnippet: `SELECT 
  c.id, 
  c.full_name, 
  c.created_at
FROM customers c
LEFT JOIN orders o ON c.id = o.customer_id
WHERE o.id IS NULL;`
      },
      {
        id: 'st-5',
        description: 'Write a CTE to calculate the month-over-month revenue and growth percentage.',
        hint: 'Define a WITH monthly_sales AS (...) and use the LAG() window function.',
        solutionSnippet: `WITH monthly_sales AS (
  SELECT 
    DATE_TRUNC('month', order_date) AS sales_month,
    SUM(order_amount) AS total_revenue
  FROM orders
  WHERE order_status = 'Completed'
  GROUP BY DATE_TRUNC('month', order_date)
)
SELECT 
  sales_month,
  total_revenue,
  LAG(total_revenue, 1) OVER (ORDER BY sales_month) AS previous_month_revenue,
  ROUND(
    (total_revenue - LAG(total_revenue, 1) OVER (ORDER BY sales_month)) * 100.0 / 
    NULLIF(LAG(total_revenue, 1) OVER (ORDER BY sales_month), 0), 2
  ) AS mom_growth_pct
FROM monthly_sales
ORDER BY sales_month;`
      }
    ],
    skillsPracticed: ['SELECT', 'WHERE filtering', 'SUM/COUNT aggregations', 'GROUP BY', 'INNER/LEFT JOIN', 'CTEs & Window Functions']
  },

  {
    id: 'pt-pbi-1',
    skillId: 'power-bi',
    careerId: 'data-analyst',
    title: 'Retail Sales Dashboard Data Modeling & DAX',
    datasetName: 'Omnichannel Superstore CSV (Orders, People, Returns)',
    datasetDescription: 'Multi-year transactional superstore dataset requiring dimensional modeling and executive DAX measure creation.',
    tasks: [
      {
        id: 'st-pbi-1',
        description: 'Import Orders and clean date columns in Power Query Editor, removing null order rows.',
        hint: 'Use Power Query "Transform" -> "Detect Data Type" and "Remove Empty".',
        solutionSnippet: `Power Query: Table.SelectRows(Orders, each [OrderID] <> null and [OrderDate] <> null)`
      },
      {
        id: 'st-pbi-2',
        description: 'Create a dedicated Date Dimension table with contiguous calendar dates and link it to Order Date (1-to-many).',
        hint: 'Use DAX: Date = CALENDARAUTO() or CALENDAR(DATE(2021,1,1), DATE(2024,12,31)).',
        solutionSnippet: `Date = 
ADDCOLUMNS(
    CALENDAR(DATE(2021,1,1), DATE(2024,12,31)),
    "Year", YEAR([Date]),
    "Month Number", MONTH([Date]),
    "Month Name", FORMAT([Date], "MMMM"),
    "Quarter", "Q" & FORMAT([Date], "Q")
)`
      },
      {
        id: 'st-pbi-3',
        description: 'Build core DAX measures: [Total Revenue], [Total Profit], and [Profit Margin %].',
        hint: 'Use SUM and DIVIDE to safely handle zero division.',
        solutionSnippet: `Total Revenue = SUM(Orders[Sales])
Total Profit = SUM(Orders[Profit])
Profit Margin % = DIVIDE([Total Profit], [Total Revenue], 0)`
      },
      {
        id: 'st-pbi-4',
        description: 'Write a Time Intelligence DAX measure to calculate [Same Period Last Year Sales].',
        hint: 'Use CALCULATE with SAMEPERIODLASTYEAR(\'Date\'[Date]).',
        solutionSnippet: `Sales SPLY = 
CALCULATE(
    [Total Revenue],
    SAMEPERIODLASTYEAR('Date'[Date])
)`
      }
    ],
    skillsPracticed: ['Power Query ETL', 'Star Schema Modeling', 'DAX Measures', 'Time Intelligence']
  },

  {
    id: 'pt-stat-1',
    skillId: 'statistics',
    careerId: 'data-analyst',
    title: 'A/B Testing & Outlier Investigation Lab',
    datasetName: 'Mobile App Checkout Redesign Experiment (40,000 Users)',
    datasetDescription: 'Experiment logs with Control (Variant A) and Test (Variant B) conversion records and purchase amounts.',
    tasks: [
      {
        id: 'st-stat-1',
        description: 'Calculate baseline conversion rate, variance, and standard deviation for both Control and Test groups.',
        hint: 'Conversion rate = converted_users / total_users. Stdev = sqrt(p * (1 - p) / n).',
        solutionSnippet: `Control: n=20,000, conv=2,400 (12.0%)
Test: n=20,000, conv=2,720 (13.6%)
Observed Absolute Lift = +1.6% (Relative Lift = +13.3%)`
      },
      {
        id: 'st-stat-2',
        description: 'Formulate Null and Alternative Hypotheses and perform a Two-Proportion Z-Test to compute the p-value.',
        hint: 'H0: p_test <= p_control. Ha: p_test > p_control. Use alpha = 0.05.',
        solutionSnippet: `Z-score = 4.82, p-value < 0.00001
Conclusion: Reject H0 with >99.9% statistical confidence. The lift is statistically significant.`
      },
      {
        id: 'st-stat-3',
        description: 'Identify fraudulent high-value transaction outliers using the IQR (Interquartile Range) rule ($Q3 + 1.5 \\times IQR$).',
        hint: 'Calculate 25th (Q1) and 75th (Q3) percentiles. Flag purchases above Q3 + 1.5*IQR.',
        solutionSnippet: `Q1 = ₹450, Q3 = ₹1,850, IQR = ₹1,400
Upper Fence = 1850 + (1.5 * 1400) = ₹3,950
All 32 orders exceeding ₹3,950 flagged for fraud audit.`
      }
    ],
    skillsPracticed: ['A/B Testing', 'Hypothesis Formulation', 'Two-Proportion Z-Test', 'IQR Outlier Detection']
  }
];
